### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by evanwhite-pyszl** [lint/nepeta-repos#4]
Hi, I'm really sorry to bother you but I couldn't find instructions to install repos like this anywhere.
I'm new to jailbreaking and would really really appreciate any help on this topic.

**Comment by lint** [comment]
Hi @Evan82378, what are you trying to install exactly? This is a collection of Nepeta's repositories that were on GitHub before she removed them. They are mostly just her tweaks' source code. If you're trying to install the packages themselves, add https://alexpng.github.io/Nepeta-Mirror/ to your package manager.

**Comment by evanwhite-pyszl** [comment]
Thank you! That's exactly what I was looking for! the chr0nict mirror wasn't working for me so this helps a lot!
